import ClayButton from '@clayui/button';
import {ClayInput} from '@clayui/form';
import ClayLayout from '@clayui/layout';
import {
	IFDSState,
	getFDSAtom,
	getFDSSearchQuerySelector,
} from '@liferay/frontend-data-set-web';
import {Atom, State} from '@liferay/frontend-js-state-web';
import {useLiferayState} from '@liferay/frontend-js-state-web/react';
import React, {useEffect, useMemo, useState} from 'react';

const CLASSIC_FDS_ATOM_NAME =
	'com_liferay_frontend_data_set_sample_web_internal_portlet_FDSSamplePortlet-classic';

/**
 * This fragment highlights sync with FDS from isolated context, if there is
 * no recommended sync method on the page. The key used is the key
 * auto-generated by FDS.
 *
 * This is not the recommended sync method. For the recommended method, see
 * "AdvancedFilters" fragment.
 */
const ClassicSearch = () => {
	const memoizedAtom = useMemo(
		() =>
			getFDSAtom({fdsName: CLASSIC_FDS_ATOM_NAME}) as Atom<IFDSState>,
		[]
	);

	const memoizedSearchQuerySelector = useMemo(
		() => getFDSSearchQuerySelector(memoizedAtom),
		[memoizedAtom]
	);

	const [fdsQuery] = useLiferayState<string>(memoizedSearchQuerySelector);

	const [query, setQuery] = useState(fdsQuery ?? '');

	useEffect(() => {
		setQuery(fdsQuery);
	}, [fdsQuery]);

	return (
		<ClayLayout.ContainerFluid>
			<ClayInput.Group className="pt-2">
				<ClayInput.GroupItem>
					<ClayInput
						className="form-control"
						component="input"
						onChange={({target: {value}}) => setQuery(value)}
						placeholder="Search in Classic tab of Frontend Data Set Sample"
						value={query}
					/>
				</ClayInput.GroupItem>

				<ClayInput.GroupItem>
					<ClayButton
						data-qa-id="classicSearchFDSSampleButton"
						onClick={() => {
							State.writeAtom(memoizedAtom, {
								...State.readAtom(memoizedAtom),
								search: {query},
							});
						}}
					>
						Search
					</ClayButton>
				</ClayInput.GroupItem>
			</ClayInput.Group>
		</ClayLayout.ContainerFluid>
	);
};

export default ClassicSearch;